services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      git pull origin main
      npm install
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 