services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.20.2
    buildFilter:
      paths:
        - package.json
        - src/**
        - prisma/**
        - next.config.js
    healthCheckPath: /
    autoDeploy: true 

# Scheduled job to run the crawler daily at 2am UTC
jobs:
  - type: cron
    name: ota-answer-hub-crawler
    env: node
    schedule: "0 2 * * *"  # Run daily at 2am UTC
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npx ts-node src/scripts/crawl.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.20.2 