services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EXPEDIA_USERNAME
        sync: false
      - key: EXPEDIA_PASSWORD
        sync: false
      - key: EXPEDIA_SESSION_COOKIE
        sync: false
      - key: BOOKING_API_TOKEN
        sync: false
      - key: BOOKING_SESSION_COOKIE
        sync: false
      - key: BOOKING_XSRF_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 18.20.2
    buildFilter:
      paths:
        - package.json
        - src/**
        - prisma/**
        - next.config.js
    healthCheckPath: /
    autoDeploy: true 

# Scheduled job to run the crawler daily at 2am UTC
jobs:
  - type: cron
    name: ota-answer-hub-crawler
    env: node
    schedule: "0 2 * * *"  # Run daily at 2am UTC
    buildCommand: |
      # Build timestamp: 2025-06-21-19:35:00 - Force rebuild for comprehensive Airbnb community scraper
      # This build includes the new comprehensive Airbnb community scraper that crawls entire site
      # Install Node.js dependencies
      npm install
      
      # Generate Prisma client and build
      npx prisma generate
      npm run build
      
      # Install Chrome for Puppeteer with proper error handling
      echo "Installing Chrome for Puppeteer..."
      npx puppeteer browsers install chrome || {
        echo "Failed to install Chrome via puppeteer browsers install, trying alternative method..."
        # Alternative: Install system Chrome if available
        apt-get update && apt-get install -y google-chrome-stable || echo "System Chrome installation failed, will use bundled Chrome"
      }
      
      # Verify Chrome installation
      echo "Verifying Chrome installation..."
      ls -la /opt/render/.cache/puppeteer/chrome/ || echo "Puppeteer cache directory not found"
      
      # Test Puppeteer setup
      echo "Testing Puppeteer setup..."
      npm run test:puppeteer-setup || echo "Puppeteer test failed, but continuing with crawl"
      
      # Force rebuild trigger for comprehensive Airbnb community scraper
      echo "BUILD_TRIGGER: Comprehensive Airbnb community scraper - $(date)"
    startCommand: npm run scrape:all
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.20.2
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
    buildFilter:
      paths:
        - package.json
        - scripts/**
        - src/**
        - prisma/**
        - VERSION 