services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      git pull origin main
      npm install --legacy-peer-deps
      npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
      - key: DATABASE_URL
        sync: false
      - key: MEILISEARCH_URL
        sync: false
      - key: MEILISEARCH_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 