services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EXPEDIA_USERNAME
        sync: false
      - key: EXPEDIA_PASSWORD
        sync: false
      - key: EXPEDIA_SESSION_COOKIE
        sync: false
      - key: BOOKING_API_TOKEN
        sync: false
      - key: BOOKING_SESSION_COOKIE
        sync: false
      - key: BOOKING_XSRF_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 18.20.2
    buildFilter:
      paths:
        - package.json
        - src/**
        - prisma/**
        - next.config.js
    healthCheckPath: /
    autoDeploy: true 

# Scheduled job to run the crawler daily at 2am UTC
jobs:
  - type: cron
    name: ota-answer-hub-crawler
    env: node
    schedule: "0 2 * * *"  # Run daily at 2am UTC
    buildCommand: |
      # Install Chrome dependencies for Puppeteer
      apt-get update && apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        wget \
        xdg-utils
      npm install
      npx puppeteer browsers install chrome
      npx prisma generate
      npm run build
    startCommand: npm run scrape
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.20.2 