services:
  - type: web
    name: ota-answer-hub
    env: node
    buildCommand: |
      git pull origin main
      npm install
      npx playwright install
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 

# Scheduled job to run the crawler daily at 2am UTC
jobs:
  - name: ota-crawler
    type: cron
    env: node
    schedule: "0 2 * * *" # every day at 2am UTC
    buildCommand: |
      npm install
      npx playwright install
      npx prisma generate
    # IMPORTANT: Install Playwright browsers every run to avoid missing executable errors
    command: npx playwright install && npx ts-node src/scripts/crawl.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    dockerCommand: |
      apt-get update && \
      apt-get install -y \
        libgtk-4-0 \
        libgraphene-1.0-0 \
        libgstgl-1.0-0 \
        libgstcodecparsers-1.0-0 \
        libenchant-2-2 \
        libsecret-1-0 \
        libmanette-0.2-0 \
        libgles2 && \
      rm -rf /var/lib/apt/lists/* 