# Render Blueprint for ota-answer-hub
# This file defines the infrastructure for the application, including a web
# service and a daily cron job. It uses an Environment Group to securely
# manage and share environment variables between the services.
# See https://render.com/docs/blueprint-spec for a detailed reference.

envVarGroups:
  - name: ota-hub-secrets
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: "18.20.2"
      # The PUPPETEER variables are essential for the cron job to install
      # and cache the Chrome browser correctly in Render's environment.
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      # Optional secrets for other data sources can be added here.
      - key: EXPEDIA_USERNAME
        sync: false
      - key: EXPEDIA_PASSWORD
        sync: false
      - key: EXPEDIA_SESSION_COOKIE
        sync: false
      - key: BOOKING_API_TOKEN
        sync: false
      - key: BOOKING_SESSION_COOKIE
        sync: false
      - key: BOOKING_XSRF_TOKEN
        sync: false
      - key: AIRBNB_USERNAME
        sync: false
      - key: AIRBNB_PASSWORD
        sync: false

services:
  # Main Next.js Web Application
  - type: web
    name: ota-answer-hub
    runtime: node
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - "src/**"
        - "prisma/**"
        - "public/**"
        - "package.json"
        - "next.config.js"
        - "render.yaml"
    envVars:
      - fromGroup: ota-hub-secrets

  # Daily cron job to scrape all configured data sources
  - type: cron
    name: ota-answer-hub-crawler
    runtime: node
    plan: starter
    schedule: "0 2 * * *" # Runs daily at 2am UTC
    autoDeploy: true
    buildCommand: |
      # Build timestamp: 2025-06-26-10:20:00 - Enhanced with database retry logic
      echo "Build started for enhanced scraper with database retry logic..."
      npm install
      npx prisma generate
      npm run build:scripts
      
      echo "Testing database connection..."
      npm run test:db || {
        echo "Database connection test failed. This might be expected in build environment."
        echo "The actual connection will be tested during runtime."
      }
      
      echo "Installing Chrome for Puppeteer..."
      npx puppeteer browsers install chrome || {
        echo "Failed to install Chrome via puppeteer. Trying system install..."
        apt-get update && apt-get install -y google-chrome-stable || echo "System Chrome installation failed. The script will rely on the bundled version."
      }
      
      echo "Verifying Chrome installation location..."
      ls -la /opt/render/.cache/puppeteer/chrome/ || echo "Puppeteer cache directory not found, which may be expected on first build."
      echo "Build scripts completed successfully."
    startCommand: npm run scrape:with-retry
    envVars:
      - fromGroup: ota-hub-secrets
    buildFilter:
      paths:
        - package.json
        - src/**
        - prisma/**
        - VERSION
        - render.yaml
        - tsconfig.json
        - tsconfig.scripts.json 