import { config } from 'dotenv';
import OpenAI from 'openai';

// Load environment variables from .env file first
config();

async function testGPTEnrichment() {
  console.log('🧪 Testing GPT-4o Report Enrichment...\n');

  // Check if API key is loaded
  if (!process.env.OPENAI_API_KEY) {
    console.error('❌ OPENAI_API_KEY not found in environment variables');
    console.log('💡 Make sure your .env file contains: OPENAI_API_KEY=your-api-key');
    return;
  }

  console.log('✅ OPENAI_API_KEY loaded successfully');

  // Initialize OpenAI client dynamically after loading .env
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });

  // Sample report content for testing
  const sampleReport = `# Tour Vendor Analytics Report

This report analyzes customer behavior patterns across major travel platforms to help tour vendors understand market opportunities and optimize their strategies.

## 📊 Platform Performance Analysis

### GetYourGuide Performance
- **Total Activities**: 15,432
- **Average Rating**: 4.3/5
- **Average Price**: €45.20
- **Top Categories**: City Tours, Food & Drink, Outdoor Activities

### Viator Performance  
- **Total Activities**: 12,891
- **Average Rating**: 4.2/5
- **Average Price**: €52.10
- **Top Categories**: Day Trips, Cultural Tours, Adventure

## 🎯 Customer Insights

### Most Popular Activities
1. **City Walking Tours** (23% of bookings)
2. **Food & Wine Experiences** (18% of bookings)
3. **Day Trips & Excursions** (15% of bookings)
4. **Adventure Activities** (12% of bookings)

### Pricing Trends
- **Budget Range** (€0-25): 15% of activities
- **Mid-Range** (€26-75): 45% of activities  
- **Premium** (€76-150): 30% of activities
- **Luxury** (€151+): 10% of activities

## 📈 Market Opportunities

### Emerging Trends
- **Sustainable Tourism**: 25% growth in eco-friendly activities
- **Local Experiences**: 18% increase in authentic local tours
- **Small Group Tours**: 22% rise in intimate group experiences
- **Digital Integration**: 30% growth in app-based tour experiences

### Seasonal Patterns
- **Peak Season** (June-August): 40% of annual bookings
- **Shoulder Season** (April-May, September-October): 35% of bookings
- **Off-Season** (November-March): 25% of bookings

## 💡 Strategic Recommendations

### Content Strategy
- Focus on trending topics like sustainable tourism and local experiences
- Develop multi-language content for international markets
- Create platform-specific content strategies

### Platform Strategy
- Primary focus on GetYourGuide for European markets
- Secondary opportunities on Viator for global reach
- Monitor emerging platforms for early adoption advantages

### Quality & Trust
- Emphasize verified content and community validation
- Build trust through transparent pricing and clear policies
- Leverage customer reviews and ratings for credibility

---

*Report generated by Hub Inbox Analytics - Your comprehensive travel content intelligence platform*`;

  try {
    console.log('📝 Original Report Content:');
    console.log('=' .repeat(50));
    console.log(sampleReport.substring(0, 300) + '...\n');

    console.log('🎯 Applying GPT-4o Enrichment...');

    // Test basic GPT-4o functionality first
    const testResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: 'Please enhance this title to be more engaging: "Tour Vendor Analytics Report"'
        }
      ],
      max_tokens: 100,
      temperature: 0.7,
    });

    console.log('✅ Basic GPT-4o test successful!');
    console.log('📝 Enhanced title:', testResponse.choices[0].message.content);

    // Now test the full enrichment process
    console.log('\n🎯 Testing full enrichment process...');
    
    // Simulate the enrichment process
    const titleEnhancement = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: `You are a content editor for a data-driven tour industry insights platform. Rewrite this title to make it more emotionally engaging and curiosity-driven: "Tour Vendor Analytics Report". Keep it under 50 words.`
        }
      ],
      max_tokens: 100,
      temperature: 0.7,
    });

    const summaryBox = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: `Generate a "What This Means for You" summary box for this report content. Make it actionable and motivating for tour vendors: ${sampleReport.substring(0, 500)}`
        }
      ],
      max_tokens: 200,
      temperature: 0.7,
    });

    const shareSuggestions = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: `Generate 3 tweet-style share suggestions for this report. Include relevant hashtags and emotional hooks: ${sampleReport.substring(0, 500)}`
        }
      ],
      max_tokens: 300,
      temperature: 0.7,
    });

    console.log('✅ Full enrichment test completed!\n');
    
    console.log('📝 Enhanced Title:');
    console.log(titleEnhancement.choices[0].message.content);
    
    console.log('\n📋 Summary Box:');
    console.log(summaryBox.choices[0].message.content);
    
    console.log('\n📱 Share Suggestions:');
    console.log(shareSuggestions.choices[0].message.content);

    console.log('\n🎉 All GPT-4o enrichment features working!');
    console.log('\nKey Features Tested:');
    console.log('✅ Title enhancement with emotional framing');
    console.log('✅ "What This Means for You" summary boxes');
    console.log('✅ Tweet-style share suggestions');
    console.log('✅ GPT-4o API connectivity');

  } catch (error) {
    console.error('❌ Error during enrichment test:', error);
    if ((error as Error).message.includes('API key')) {
      console.log('\n💡 The API key might be invalid or expired. Please check your OpenAI API key.');
    }
  }
}

// Run the test if this file is executed directly
if (require.main === module) {
  testGPTEnrichment()
    .then(() => {
      console.log('\n🏁 Test finished');
      process.exit(0);
    })
    .catch((error) => {
      console.error('💥 Test failed:', error);
      process.exit(1);
    });
} 