#!/bin/bash

echo "🔧 UPDATING RENDER ENVIRONMENT VARIABLE"
echo "======================================"
echo ""

echo "Current issue: NEXT_PUBLIC_BASE_URL is pointing to wrong domain"
echo "This is causing 1,255 sitemap errors in Google Search Console"
echo ""

echo "🚀 MANUAL STEPS TO FIX:"
echo "======================="
echo ""
echo "1. Go to Render Dashboard:"
echo "   https://dashboard.render.com"
echo ""
echo "2. Find your service (ota-answer-hub-1woc)"
echo ""
echo "3. Click on 'Environment' tab"
echo ""
echo "4. Find NEXT_PUBLIC_BASE_URL"
echo ""
echo "5. Change the value to: https://otaanswers.com"
echo ""
echo "6. Click 'Save Changes'"
echo ""
echo "7. Your app will automatically redeploy"
echo ""
echo "8. Wait for deployment to complete (2-3 minutes)"
echo ""
echo "9. Go to Google Search Console:"
echo "   https://search.google.com/search-console"
echo ""
echo "10. Remove old sitemap: https://otaanswers.com/sitemap.xml"
echo ""
echo "11. Add new sitemap: https://otaanswers.com/sitemap.xml"
echo ""
echo "12. Request indexing for:"
echo "    https://otaanswers.com/reports/airbnb-ranking-algorithm-complete-guide-for-hosts-2025"
echo ""
echo "✅ After these steps, your sitemap errors should be resolved!"
echo "✅ Your Airbnb report should be indexed within 24-48 hours"
echo ""

# Check if we can verify the fix
echo "🔍 VERIFICATION:"
echo "================"
echo "After updating, test these URLs:"
echo ""
echo "Sitemap: https://otaanswers.com/sitemap.xml"
echo "Report: https://otaanswers.com/reports/airbnb-ranking-algorithm-complete-guide-for-hosts-2025"
echo ""

echo "📱 DON'T FORGET:"
echo "================"
echo "While waiting for indexing, promote your report on social media:"
echo "- LinkedIn (Airbnb host groups)"
echo "- Twitter/X (vacation rental community)"
echo "- Facebook (Airbnb host communities)"
echo "- Reddit (r/AirBnBHosts)"
echo ""
echo "This will help drive traffic and signal to Google that the page is valuable." 